# Generated by Django 3.2 on 2021-05-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categorie'),
        ),
    ]
